ASSIGNED - bug 1403: Missing class for PMD type resolution on sierra-services https://fluid.surelogic.com/bugzilla/show_bug.cgi?id=1403
Added code to try and deal w/ NoClassDefFoundError (e.g. problems finding classes that it depends on)

git-svn-id: https://fluid.surelogic.com/svn/eng/trunk/sierra-tool@6398 d02ae147-ee12-4a35-9452-91c89e8b2592