ASSIGNED - bug 1413: (SureLogic #46) Scan job 'Running Sierra on Tomcat' failed before it completed. https://fluid.surelogic.com/bugzilla/show_bug.cgi?id=1413
Changed to convert NoClassDefFoundErrors into ClassNotFoundExceptions

git-svn-id: https://fluid.surelogic.com/svn/eng/trunk/sierra-tool@6625 d02ae147-ee12-4a35-9452-91c89e8b2592